### ISSUE TITLE
 ERROR:  DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14

### ISSUE THREAD

**Issue by ajlinux** [tds-fdw/tds_fdw#105] opened 2016-11-10 13:00 UTC
Hi 

I was wondering if you could help.  Trying to use tds_fdw to talk to SQL Server 2016 and 2014 databases. One of them is UTF-16 encoded and I believe has null characters. We are getting the following error when we try to query the view we have created.  Am running Postgresql 9.6.

ERROR:  DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14

********** Error **********

ERROR: DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14
SQL state: HV00L

Any thoughts on how to resolve this.  Am running tds 1.0.8 - also tried 2.0.0 alpha and get the same version.  Running version 1.0 of free_tds.

I am not using a DSN for the server but am creating the server directly in postgres.

Would really appreciate your help.

**Comment by GeoffMontee** [comment] 2016-11-10 18:31
Hi @ajlinux,

When you see a message like this:

```
ERROR:  DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 14
```

It means that the remote server rejected the query for some reason. You can usually get more information by setting `msg_handler` to `notice` for the foreign server.

```
ALTER SERVER svr
   OPTIONS (ADD msg_handler 'notice');
```

**Comment by ajlinux** [comment] 2016-11-18 12:32
Hi Geoff

Thanks I am getting the following error now:

NOTICE: DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'db_1'., Server: 06\SQLSUBS, Process: , Line: 1, Level: 0 NOTICE: DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: 06\SQLSUBS, Process: , Line: 1, Level: 0 NOTICE: DB-Library notice: Msg #: 262, Msg state: 4, Msg: SHOWPLAN permission denied in database 'db_1'., Server: 06\SQLSUBS, Process: , Line: 1, Level: 14 Query returned successfully in 114 msec.

**Comment by GeoffMontee** [comment] 2016-11-18 15:41
It looks like you do not have permission to execute `SET SHOWPLAN_ALL`, so you will have to either request that permission for your user account or set the [row_estimate_method foreign table option](https://github.com/tds-fdw/tds_fdw/blob/master/ForeignTableCreation.md) to `execute` rather than `showplan_all`.

**Comment by Smtgr14** [comment] 2016-12-29 15:26
@ajlinux Did using the option ```row_estimate_method 'execute'``` work?
Or are you still experiencing this issue?

**Comment by retsel0707** [comment] 2017-05-26 00:18
I have the same issue but when i try to add the msg_handler in the foreign server options...I get the following error...

NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'SampleDB'., Server: testserver, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 2809, Msg state: 1, Msg: The request for procedure 'test_table' failed because 'test_table' is a table object., Server: testserver, Process: , Line: 1, Level: 18

**Comment by retsel0707** [comment] 2017-06-01 02:27
Hi @Smtgr14 thanks for the reply.

Here is the sample definition of one of the foreign tables.

`-- Foreign Table: SampleDB.test_table

-- DROP FOREIGN TABLE SampleDB.test_table;

CREATE FOREIGN TABLE SampleDB.test_table
   (rec_id integer NOT NULL,
    product_code character(10) ,
    product_amt numeric(19,4) ,
    date_saved timestamp without time zone ,
    saved_by character varying(6) ,
    record_status character(1))
   SERVER testserver
   OPTIONS (query 'SELECT
	rec_id,
	product_code,
	product_amt,
	CONVERT(datetime2, date_saved) as date_saved,
	saved_by,
	record_status
FROM dbo.test_table');
ALTER FOREIGN TABLE SampleDB.test_table
  OWNER TO postgres;
`

**Comment by Smtgr14** [comment] 2017-06-02 22:55
I'm not sure if this is the cause, but it seems to be missing from your definition based on the previous error.
```ALTER FOREIGN TABLE SampleDB.test_table OPTIONS (ADD row_estimate_method 'EXECUTE');```
If all else fails, try wrapping your MS SQL query on a view on the MS SQL side and then query that view directly using PostgreSQL.

**Comment by Smtgr14** [comment] 2017-06-05 16:04
I'm not understanding, are you still having issues?
If not, please close this issue.

**Comment by retsel0707** [comment] 2017-06-05 23:49
No I'm not having issues anymore...Thanks for all the help...
close #105

**Comment by Smtgr14** [comment] 2017-06-06 17:46
Should be a close button near the "Comment" button.
Or @GeoffMontee can close it if he sees this first.

**Comment by GeoffMontee** [comment] 2017-06-06 17:56
I can close it. Thanks, @Smtgr14! I really appreciate that you've been helping out tds_fdw users.

**Closed by GeoffMontee** 2017-06-06 17:56 UTC
