### ISSUE TITLE
Cannot use WHERE clause on foreign tables using a DateTime type

### ISSUE THREAD

**Issue by Smtgr14** [tds-fdw/tds_fdw#82] opened 2016-07-08 21:43 UTC
When I run this query:
```
SELECT * FROM performance.cisco_agent_event_detail
WHERE "DateTime" >= '2016-07-01 00:00:00'
```
I get this error:
```
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'ga_awdb'., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 102, Msg state: 1, Msg: Incorrect syntax near 'without'., Server: NOVAHDS01, Process: , Line: 1, Level: 15
ERROR:  DB-Library error: DB #: 102, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 15
********** Error **********

ERROR: DB-Library error: DB #: 102, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 15
SQL state: HV00L

```

If I leave out the WHERE clause or use a condition that does not look at a DateTime field, the query executes with no issue.

This is my foreign table definition:
```
CREATE FOREIGN TABLE performance.cisco_agent_event_detail
   ("DateTime" timestamp without time zone NOT NULL,
    "SkillTargetID" integer NOT NULL,
    "MRDomainID" integer NOT NULL,
    "TimeZone" integer NOT NULL,
    "LoginDateTime" timestamp without time zone NOT NULL,
    "Event" integer NOT NULL,
    "RecoveryKey" double precision NOT NULL,
    "Duration" integer ,
    "ReasonCode" integer ,
    "DbDateTime" timestamp without time zone )
   SERVER ga_awdb
   OPTIONS (table 'dbo.Agent_Event_Detail', row_estimate_method 'execute');
```

**Comment by Smtgr14** [comment] 2016-07-08 21:52
It looks like if I query:
```
SELECT * FROM performance.cisco_agent_event_detail
WHERE "DateTime"::date >= '2016-07-01'
```
There are no issues.
I guess the problem is specifically using a DateTime field that's been defined as a timestamp without time zone.

**Comment by GeoffMontee** [comment] 2016-07-08 22:54
Thanks for the bug report!

This is probably related to issue #73.

tds_fdw is probably sending the remote server some query like:

```
SELECT * FROM dbo.Agent_Event_Detail
WHERE "DateTime" >= CAST('2016-07-01 00:00:00' AS timestamp without timezone);
```

Since `timestamp without timezone` is not a valid [SQL Server data type](https://msdn.microsoft.com/en-us/library/ms187752.aspx), this query would probably return a syntax error similar to the one you are seeing:

```
NOTICE:  DB-Library notice: Msg #: 102, Msg state: 1, Msg: Incorrect syntax near 'without'., Server: NOVAHDS01, Process: , Line: 1, Level: 15
```

For now, you can get around this by disabling where pushdowns for this table, by disabling `match_column_names`, similar to how I described in issue #77.

**Comment by Smtgr14** [comment] 2016-07-09 00:14
Does tds_fdw not translate timestamp without timezone into DateTime and vice versa?

**Comment by Smtgr14** [comment] 2016-07-09 00:21
I've worked out that using a materialized view allows the data to load properly, where I can then apply WHERE clauses. I'd prefer the push down support since the table is over 1.5 M rows, but this will function in the interim.

**Comment by GeoffMontee** [comment] 2016-07-09 00:24
> Does tds_fdw not translate timestamp without timezone into DateTime and vice versa?

Yes, tds_fdw maps timestamps without timezone to the relevant SQL Server type. The problem here is specifically related to WHERE pushdowns. The deparse code that implements WHERE pushdowns was ported from postgres_fdw, and there are still weird bugs in cases where SQL Server behaves differently from PostgreSQL. That's why 2.0.0 was released as an alpha release.

This bug seems like it will be easy to fix, but I probably won't be able to get to it tonight.

**Comment by GeoffMontee** [comment] 2016-07-10 17:09
The latest commit maps timestamp constants in WHERE pushdowns on the PostgreSQL side to datetime2 constants on the SQL Server side: https://github.com/tds-fdw/tds_fdw/commit/fd9b453805df2812d4c210cc1b39870a4eb26778

Please let me know if you still have this issue with the latest commit, or if you notice any similar issues with other data types.

**Comment by Smtgr14** [comment] 2016-07-11 17:07
It looks like datetime2 isn't the proper type...
```
SELECT * FROM performance.cisco_agent_event_detail WHERE "DateTime" >= '2016-07-11 10:00:00';'                                                            
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'ga_awdb'., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: NOVAHDS01, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 243, Msg state: 1, Msg: Type datetime2 is not a defined system type., Server: NOVAHDS01, Process: , Line: 1, Level: 16
ERROR:  DB-Library error: DB #: 243, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 16
```

The same error gets thrown but now for datetime2, we must be getting there.
As a side note, do you have a tip jar or something? I'd like to buy you a beer/coffee.

**Comment by GeoffMontee** [comment] 2016-07-11 17:11
> It looks like datetime2 isn't the proper type...

Hmm, that's strange. The fix worked for me when I tested it on Azure database (which should work just like Microsoft SQL Server). What is your remote database running on? Is it Sybase?

Also, what is the definition of `dbo.Agent_Event_Detail` on the remote server?

> As a side note, do you have a tip jar or something? I'd like to buy you a beer/coffee.

Thanks! I appreciate that. I don't have anything set up for receiving donations right now, but I might set something up in the future.

**Comment by Smtgr14** [comment] 2016-07-11 17:26
The DB I'm pulling from is MS SQL 2005. I cannot provide the definition of the remote table, but it's date time fields are typed as (DBDATETIME(datetime), not null). It's actually a contact center call router database.

I forked the repo and dropped the '2' from the datetime2 in the deparse.c file. It's working on my side. Even if this is merely a temporary fix, it's good on my end. Not sure why your fix worked for you and not me though, maybe it's because 2005 is such an old, virtually useless version? We really need to upgrade.

**Comment by Smtgr14** [comment] 2016-07-11 17:36
Now it gets really interesting... after implementing my duct tape-esque fix, the query works, until I run the exact same query again when I get:
```ERROR:  DB-Libary error: DB #: 2402, DB Msg: Error converting characters into server's character set. Some character(s) could not be converted, OS #: 0, OS Msg: Success, Level: 4```

**Comment by GeoffMontee** [comment] 2016-07-11 18:26
> The DB I'm pulling from is MS SQL 2005.

Ah, I see. It sounds like the `datetime2` type was added in SQL Server 2008.

I'm not actually sure that tds_fdw gains many benefits from the way it wraps constants in CAST by default. This is behavior that tds_fdw inherited from postgres_fdw. I'm pretty sure SQL Server can handle interpreting datetime literals without the CAST. I might decide to default `needlabel` to false instead of true, so that these kinds of issues can be avoided: https://github.com/tds-fdw/tds_fdw/blob/fd9b453805df2812d4c210cc1b39870a4eb26778/src/deparse.c#L1382

**Comment by Smtgr14** [comment] 2016-07-11 18:38
Neat. I'm fairly certain that even MS SQL 2005 handles timestamps implicitly as long as they are in the 'YYYY-MM-DD HH:MM:SS' format or similar.
So, I've determined the error:
```ERROR: DB-Libary error: DB #: 2402, DB Msg: Error converting characters into server's character set. Some character(s) could not be converted, OS #: 0, OS Msg: Success, Level: 4```
Only occurs for queries repeated within the same session. Disconnecting and reconnecting lets you run the query again.

**Comment by GeoffMontee** [comment] 2016-07-11 18:54
> Only occurs for queries repeated within the same session. Disconnecting and reconnecting lets you run the query again.

It looks like it's actually caused by running two queries that will both cause errors. The error message after the first message gets changed for some reason.

Running two working queries that should both work seems to work fine for me. Example:

```
postgres=# select * from datetime2 where value > '2015-10-22';
ERROR:  DB-Library error: DB #: 20018, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 15
postgres=# select * from datetime2 where value > '2015-10-22';
ERROR:  DB-Library error: DB #: 2402, DB Msg: Error converting characters into server's character set. Some character(s) could not be converted, OS #: 0, OS Msg: Success, Level: 4
postgres=# select * from datetime2 where value > '2015-10-22';
ERROR:  DB-Library error: DB #: 2402, DB Msg: Error converting characters into server's character set. Some character(s) could not be converted, OS #: 0, OS Msg: Success, Level: 4
postgres=# select * from datetime2 where value > '2015-10-22'::date;
 id |        value
----+---------------------
  1 | 2015-10-22 11:01:02
(1 row)

postgres=# select * from datetime2 where value > '2015-10-22'::date;
 id |        value
----+---------------------
  1 | 2015-10-22 11:01:02
(1 row)

postgres=# select * from datetime2 where value > '2015-10-22'::date;
 id |        value
----+---------------------
  1 | 2015-10-22 11:01:02
(1 row)
```

**Comment by GeoffMontee** [comment] 2016-07-11 19:04
The latest commit sets needlabel=false by default: https://github.com/tds-fdw/tds_fdw/commit/708036c0348b3431e54cb6c76a76deeff7297474

**Comment by Smtgr14** [comment] 2016-07-11 19:27
The latest commit you did fixes the repeating query issue. I still have to modify the datetime2 to datetime for it to work. Is there a way you can add a check or option for this?
In any case case, I owe you a few beers, dates and times make programming really hard.

**Comment by GeoffMontee** [comment] 2016-07-11 19:32
> The latest commit you did fixes the repeating query issue. I still have to modify the datetime2 to datetime for it to work. Is there a way you can add a check or option for this?

Hmm, that would mean that it's still printing the `CAST( ... AS datetime2)` for you, but if `needlabel` is false, then this code should not be getting executed at all: https://github.com/tds-fdw/tds_fdw/blob/708036c0348b3431e54cb6c76a76deeff7297474/src/deparse.c#L1432

Did you recompile everything and reinstall based on the latest commit?

> In any case case, I owe you a few beers, dates and times make programming really hard.

Haha, thanks!

**Comment by Smtgr14** [comment] 2016-07-11 19:35
Silly me, I didn't reset my changes properly.
Everything works perfectly from the latest commit! Thanks so much! If I come across anything else, I'll open a relevant issue.

**Comment by GeoffMontee** [comment] 2016-07-11 19:46
Awesome! I'm glad to hear that it's working now.

**Closed** 2016-08-24 20:44 UTC

**Comment by custom-component-gratify** [comment] 2025-02-02 11:12
> It looks like datetime2 isn't the proper type...
> 
> ```
> SELECT * FROM performance.cisco_agent_event_detail WHERE "DateTime" >= '2016-07-11 10:00:00';'                                                            
> NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'ga_awdb'., Server: NOVAHDS01, Process: , Line: 1, Level: 0
> NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: NOVAHDS01, Process: , Line: 1, Level: 0
> NOTICE:  DB-Library notice: Msg #: 243, Msg state: 1, Msg: Type datetime2 is not a defined system type., Server: NOVAHDS01, Process: , Line: 1, Level: 16
> ERROR:  DB-Library error: DB #: 243, DB Msg: General SQL Server error: Check messages from the SQL Server, OS #: -1, OS Msg: (null), Level: 16
> ```
> 
> The same error gets thrown but now for datetime2, we must be getting there. As a side note, do you have a tip jar or something? I'd like to buy you a beer/coffee.





https://stackdev.space/questions/what-criteria-should-one-consider-when-choosing-using-a-where-clause
